// <auto-generated />
using System;
using HRD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRD.Models.Division", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "001",
                            Name = "АУП"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "002",
                            Name = "Бухгалтерия"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "003",
                            Name = "Техническая служба"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "004",
                            Name = "ИТ"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "005",
                            Name = "СПИР"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "006",
                            Name = "Дворники"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "007",
                            Name = "Горничные"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "008",
                            Name = "Отдел связи"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "009",
                            Name = "СПА"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "010",
                            Name = "Бассейн"
                        });
                });

            modelBuilder.Entity("HRD.Models.DivisionMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<long?>("ParentDivisionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("ParentDivisionId");

                    b.ToTable("DivisionMovements");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 2L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 2L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 3L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 3L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 4L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 4L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 5L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 5L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 6L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 6L,
                            MovementType = 0,
                            ParentDivisionId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 7L,
                            MovementType = 0,
                            ParentDivisionId = 5L
                        },
                        new
                        {
                            Id = 8L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 8L,
                            MovementType = 0,
                            ParentDivisionId = 4L
                        },
                        new
                        {
                            Id = 9L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 9L,
                            MovementType = 0,
                            ParentDivisionId = 5L
                        },
                        new
                        {
                            Id = 10L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 10L,
                            MovementType = 0,
                            ParentDivisionId = 9L
                        },
                        new
                        {
                            Id = 11L,
                            Date = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 4L,
                            MovementType = 2,
                            ParentDivisionId = 3L
                        });
                });

            modelBuilder.Entity("HRD.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Василий",
                            Patronymic = "Олегович",
                            Surname = "Петров"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Петр",
                            Patronymic = "Михайлович",
                            Surname = "Иванов"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Матвей",
                            Patronymic = "Вячеславович",
                            Surname = "Качуровский"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Екатерина",
                            Patronymic = "Юрьевна",
                            Surname = "Шабунина"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Атнонина",
                            Patronymic = "Николаевна",
                            Surname = "Бочарникова"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Юлия",
                            Patronymic = "Михайловна",
                            Surname = "Шумкова"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Борис",
                            Patronymic = "Борисович",
                            Surname = "Шимякин"
                        });
                });

            modelBuilder.Entity("HRD.Models.EmployeeMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeMovements");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1L,
                            EmployeeId = 1L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 2L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1L,
                            EmployeeId = 2L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 3L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 4L,
                            EmployeeId = 3L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 4L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 5L,
                            EmployeeId = 4L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 5L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 3L,
                            EmployeeId = 5L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 6L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 2L,
                            EmployeeId = 6L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 7L,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 10L,
                            EmployeeId = 7L,
                            MovementType = 0
                        },
                        new
                        {
                            Id = 8L,
                            Date = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DivisionId = 1L,
                            EmployeeId = 4L,
                            MovementType = 2
                        });
                });

            modelBuilder.Entity("HRD.Models.DivisionMovement", b =>
                {
                    b.HasOne("HRD.Models.Division", "Division")
                        .WithMany("DivisionMovements")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRD.Models.Division", "ParentDivision")
                        .WithMany("SubdivisionMovements")
                        .HasForeignKey("ParentDivisionId");

                    b.Navigation("Division");

                    b.Navigation("ParentDivision");
                });

            modelBuilder.Entity("HRD.Models.EmployeeMovement", b =>
                {
                    b.HasOne("HRD.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRD.Models.Employee", "Employee")
                        .WithMany("EmployeeMovements")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRD.Models.Division", b =>
                {
                    b.Navigation("DivisionMovements");

                    b.Navigation("SubdivisionMovements");
                });

            modelBuilder.Entity("HRD.Models.Employee", b =>
                {
                    b.Navigation("EmployeeMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
